name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install and build"
      - run: npm i
      - run: npm ci
      - run: npm run build --if-present

      - name: "Run prettier"
      - run: npm npm run prettier

      - name: "Run linter"
      - run: npm run linter

      - name: "Test"
      - run: npm test
